### ISSUE TITLE
Where do you override the generate method while inference (BART)

### ISSUE THREAD

**Issue by zuujhyt** [j-min/VL-T5#10]
Hello,
I saw the code in the ```text_step```
```
            output = self.generate(
                input_ids=input_ids,
                vis_inputs=(vis_feats, vis_pos),
            )
```
THe original Huggingface BART's ```generate``` function didn't include your newly defined ```vis_inputs```,
where do you overide it?
Thank you.

**Comment by cooelf** [comment]
@zuujhyt Hi, I have the same question. Did you figure out how to override the generate method while inference?

Thanks.

**Comment by j-min** [comment]
I didn't change the `generate` method of GenerationMixin class. [The `generate` method indeed supports to use extra parameters via `**kwargs`](https://github.com/huggingface/transformers/blob/v4.26.0/src/transformers/generation/utils.py#L1095-L1104)

Instead of changing `generate`, I updated the methods (prepare_inputs_for_generation, _expand_inputs_for_generation) that are used in `generate` that use `**kwargs`, as I did in modeling_t5.py and [modeling_bart.py](https://github.com/j-min/VL-T5/blob/main/VL-T5/src/modeling_bart.py#L497-L553)
